class_name InteractionCatalog
extends RefCounted


enum Id {
	WAYSTONE,
	BRAM_WORKBENCH,
	EASTERN_CROSSING,
	FIELD_MAP,
	RIFTGLASS_SHARD,
	HOUND_MEMORY,
	GLASSWOOD_SHRINE,
	AMBERFEN_ORRERY,
	BELLSCAR_BELL,
	IVEN_VOICE,
	SOLA_VOICE,
	ORIN_VOICE,
	THREE_VOICES_GATE,
	CROSSING_AFTERMATH,
	GLASS_ROAD_BEACON,
}
