class_name ItemCatalog
extends RefCounted


enum Id {
	NONE = -1,
	RIFTGLASS,
	LANTERN_LENS,
	ASTER_MEMORY,
	GLASSWOOD_RESONANCE,
	AMBER_ORBIT,
	BELLSCAR_ECHO,
	RESCUED_IVEN,
	RESCUED_SOLA,
	RESCUED_ORIN,
	MEMORY_THREAD,
	MEMORY_COMPASS,
	CAUSEWAY_IVEN_VOICE,
	CAUSEWAY_SOLA_VOICE,
	CAUSEWAY_ORIN_VOICE,
	CROSSING_CHOICE_SHELTER,
	CROSSING_CHOICE_BRIDGE,
	CROSSING_CHOICE_WITNESS,
}
