class_name LumenfallTypes
extends RefCounted


enum QuestStage {
	SUMMONED,
	WAKE_WAYSTONE,
	MEET_MARA,
	GATHER_RIFTGLASS,
	RETURN_SHARDS_TO_BRAM,
	CRAFT_LANTERN_LENS,
	SHOW_LENS_TO_MARA,
	REACH_EASTERN_CROSSING,
	DEFEND_LANTERN_ROAD,
	LISTEN_TO_ASTER,
	REPORT_ASTER,
	CHOOSE_REGION,
	DISCOVER_REGION_INSTRUMENT,
	MARK_REGION_DISCOVERY,
	REPORT_THREE_INSTRUMENTS,
	RESCUE_MISSING_VILLAGERS,
	RETURN_THREE_NAMES,
	CRAFT_MEMORY_COMPASS,
	BRING_COMPASS_TO_WAYSTONE,
	AWAKEN_CAUSEWAY_VOICES,
	ANSWER_CAUSEWAY_GATE,
	REPORT_CROSSING_ANSWER,
	EXAMINE_CROSSING_AFTERMATH,
	FOLLOW_GLASS_ROAD,
}

enum QuestId {
	THE_WRONG_STAR,
	WAKE_THE_WAYSTONE,
	THE_ANSWERING_SKY,
	THE_SINGING_SHARDS,
	RIFTGLASS_IS_NOT_COIN,
	A_LENS_FOR_THE_ROAD,
	THE_GUARDIANS_MEASURE,
	BEYOND_THE_LANTERNS,
	THE_HOUND_CALLED_ASTER,
	A_NAME_INSIDE_THE_NOISE,
	THE_NAME_ASTER,
	HEARTHMERE_WAGES,
	THE_FIRST_CROSSING,
	GLASSWOOD_CALL,
	AMBERFEN_ORBIT,
	BELLSCAR_WAKE,
	THREE_INSTRUMENTS_ANSWERED,
	THE_THREE_INSTRUMENTS,
	THE_CROSSING_OF_THREE_VOICES,
	THREE_NAMES_RETURNED,
	FORGE_THE_MEMORY_COMPASS,
	NAMES_IN_THE_WIND,
	COMPASS_TO_THE_WAYSTONE,
	CROSSING_OF_THREE_VOICES,
	THE_ROAD_ASKS,
	ANSWER_CARRIED_HOME,
	HEARTHMERE_AFTER_THE_ANSWER,
	THE_GLASS_ROAD,
}

enum NpcId {
	NIA,
	BRAM,
	MARA,
	PIP,
	IVEN,
	SOLA,
	ORIN,
}

enum InteractionId {
	WAYSTONE,
	BRAM_WORKBENCH,
	EASTERN_CROSSING,
	FIELD_MAP,
	RIFTGLASS_SHARD,
	HOUND_MEMORY,
	GLASSWOOD_SHRINE,
	AMBERFEN_ORRERY,
	BELLSCAR_BELL,
	IVEN_VOICE,
	SOLA_VOICE,
	ORIN_VOICE,
	THREE_VOICES_GATE,
	CROSSING_AFTERMATH,
	GLASS_ROAD_BEACON,
}

enum ItemId {
	RIFTGLASS,
	LANTERN_LENS,
	ASTER_MEMORY,
	GLASSWOOD_RESONANCE,
	AMBER_ORBIT,
	BELLSCAR_ECHO,
	RESCUED_IVEN,
	RESCUED_SOLA,
	RESCUED_ORIN,
	MEMORY_THREAD,
	MEMORY_COMPASS,
	CAUSEWAY_IVEN_VOICE,
	CAUSEWAY_SOLA_VOICE,
	CAUSEWAY_ORIN_VOICE,
	CROSSING_CHOICE_SHELTER,
	CROSSING_CHOICE_BRIDGE,
	CROSSING_CHOICE_WITNESS,
}

enum RecipeId {
	LANTERN_LENS,
	MEMORY_COMPASS,
}

enum RegionId {
	GLASSWOOD,
	AMBERFEN,
	BELLSCAR,
}

enum CrossingChoice {
	NONE = -1,
	SHELTER,
	BRIDGE,
	WITNESS,
}

enum AssetId {
	BRAM,
	COTTAGE_BLUE,
	COTTAGE_RED,
	IVEN,
	LANTERN_POST,
	MARA,
	NIA,
	OAK,
	ORIN,
	PINE,
	PIP,
	RIFT_HOUND,
	SOLA,
	VILLAGE_PROPS,
	WAYFARER,
	WAYSTONE,
}

enum PhysicsLayer {
	NONE = 0,
	WORLD = 1,
	PLAYER = 2,
	ENEMY = 4,
}

enum TutorialStage {
	NOT_STARTED,
}


static func asset_file_name(asset_id: AssetId) -> String:
	return String(AssetId.find_key(asset_id)).to_snake_case()


static func npc_asset(npc_id: NpcId) -> AssetId:
	match npc_id:
		NpcId.NIA:
			return AssetId.NIA
		NpcId.BRAM:
			return AssetId.BRAM
		NpcId.MARA:
			return AssetId.MARA
		NpcId.PIP:
			return AssetId.PIP
		NpcId.IVEN:
			return AssetId.IVEN
		NpcId.SOLA:
			return AssetId.SOLA
		NpcId.ORIN:
			return AssetId.ORIN
	return AssetId.WAYFARER


static func crossing_choice_item(choice: LumenfallTypes.CrossingChoice) -> LumenfallTypes.ItemId:
	match choice:
		CrossingChoice.SHELTER:
			return ItemId.CROSSING_CHOICE_SHELTER
		CrossingChoice.BRIDGE:
			return ItemId.CROSSING_CHOICE_BRIDGE
		CrossingChoice.WITNESS:
			return ItemId.CROSSING_CHOICE_WITNESS
	return ItemId.CROSSING_CHOICE_WITNESS
